import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Script from "next/script";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        {/* eslint-disable-next-line @next/next/no-before-interactive-script-outside-document */}
        <Script
          id="weglot-lib"
          src="https://cdn.weglot.com/weglot.min.js"
          strategy="beforeInteractive"
        />
        <Script
          strategy="lazyOnload"
          id="weglot-initialize"
        >{`if(Weglot){Weglot.initialize({ api_key: 'wg_6e8cd45412c48c12621cf05910422b335'})}`}</Script>
      </head>
      <body className={inter.className}>{children}</body>
    </html>
  );
}
